"use strict";
// let x = 20;
// let y = 10;
// let sum = x + y;
// console.log("Sum: ", sum);
// let a = 50;
// let b = 40;
// let sub = a - b;
// console.log("sub: ", sub);
// let g = 7;
// let h = 8;
// let mult = g * h;
// console.log("mult: ", mult);
// let c = 8;
// let d = 2;
// let division = c / d;
// console.log("division: ", division);
// let t = 8;
// let m = 4;
// let exponent = t ** d;
// console.log("exponent: ", exponent);
let x = 20;
let y = 10;
let sum = x + y;
console.log("Sum: ", sum)
let sub = x - y;
console.log("sub: ", sub);
let mult = x * y;
console.log("mult: ", mult);
let division = x / y;
console.log("division: ", division);
let exponent = x ** y;
console.log("exponent: ", exponent);