"use strict";
let x = 20;
let y = 10;
let sum = x + y;
console.log("Sum: ", sum);
let a = 50;
let b = 40;
let suma = a - b;
console.log("Suma: ", suma);
let g = 7;
let h = 8;
let mult = g * h;
console.log("mult: ", mult);
let c = 8;
let d = 2;
let division = c / d;
console.log("division: ", division);
let t = 4;
let m = 2;
let expon = t ** m;
console.log("expon: ", expon);
